name: Mark stale PRs

on:
  schedule:
    - cron: '30 1 * * *'  # Run at 1:30 UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR has been inactive for 30 days. It will be closed in 5 days if there is no activity.'
          close-pr-message: 'This PR was closed due to inactivity.'
          days-before-pr-stale: 30
          days-before-pr-close: 5
          stale-pr-label: 'stale'
          exempt-pr-labels: 'work-in-progress,do-not-close'
          operations-per-run: 30
