name: Test and Validate

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - '**.json'
      - 'src/**'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.json'
      - 'src/**'
      - 'scripts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate JSON schemas
      run: |
        python scripts/validate_schema.py
        
    - name: Validate data quality (if data exists)
      run: |
        if [ -f "docs/api/latest.json" ]; then
          python scripts/validate_data_quality.py
        else
          echo "No data file found, skipping data quality validation"
        fi
      continue-on-error: true  # Don't fail on missing data in PRs
        
    - name: Lint code
      run: |
        python -m flake8 src/ scripts/ --max-line-length=100 --extend-ignore=E203,W503
      continue-on-error: true  # Don't fail CI on linting issues
        
    - name: Type check
      run: |
        python -m mypy src/ --ignore-missing-imports
      continue-on-error: true  # Don't fail CI on type checking issues