name: Validate Schema

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/api/**'
      - 'reports/**'
      - 'schemas/**'
      - 'src/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
          
      - name: Validate JSON schema
        run: |
          python scripts/validate_schema.py
          
      - name: Run tests
        run: |
          pip install pytest
          pip install -r requirements.txt
          python -m pytest tests/test_json_generator.py -v
