name: Weekly GitHub Signals Report

on:
  schedule:
    # Run weekly on Monday at 9:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate weekly report
      run: |
        ./run_weekly_gems.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push generated reports
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        
        # Add generated files
        git add reports/ docs/
        
        # Commit changes (if any)
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📊 Update weekly signals report [$(date +%Y-%m-%d)]"
          git push
        fi

    - name: Upload report artifact
      uses: actions/upload-artifact@v3
      with:
        name: weekly-report
        path: |
          reports/
          docs/api/
